"""Add ProductDocuments table

Revision ID: cb24bf16b8d3
Revises: e6f7g8h9i0j1
Create Date: 2025-12-16 00:08:05.840002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb24bf16b8d3'
down_revision: Union[str, Sequence[str], None] = 'e6f7g8h9i0j1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ProductDocuments',
    sa.Column('Id', sa.String(length=36), nullable=False),
    sa.Column('ProductId', sa.String(length=36), nullable=False),
    sa.Column('FileUrl', sa.String(length=1000), nullable=False),
    sa.Column('FileName', sa.String(length=500), nullable=True),
    sa.Column('ContentType', sa.String(length=255), nullable=True),
    sa.Column('FileSize', sa.Integer(), nullable=True),
    sa.Column('SortOrder', sa.Integer(), nullable=False),
    sa.Column('IsDeleted', sa.Boolean(), nullable=False),
    sa.Column('CreatedAt', sa.DateTime(), nullable=False),
    sa.Column('CreatedBy', sa.String(length=36), nullable=True),
    sa.Column('UpdatedAt', sa.DateTime(), nullable=True),
    sa.Column('UpdatedBy', sa.String(length=36), nullable=True),
    sa.Column('DeletedAt', sa.DateTime(), nullable=True),
    sa.Column('DeletedBy', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['ProductId'], ['Products.Id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    op.drop_index(op.f('OrderNumber'), table_name='Orders')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('OrderNumber'), 'Orders', ['OrderNumber'], unique=True)
    op.drop_table('ProductDocuments')
    # ### end Alembic commands ###

