"""Initial migration - create all tables

Revision ID: d5be0f3a7f92
Revises: 
Create Date: 2025-11-30 22:08:52.934649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5be0f3a7f92'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('BlogCategories',
    sa.Column('Id', sa.String(length=36), nullable=False),
    sa.Column('Title', sa.String(length=255), nullable=False),
    sa.Column('TitleEn', sa.String(length=255), nullable=True),
    sa.Column('TitleAr', sa.String(length=255), nullable=True),
    sa.Column('Slug', sa.String(length=255), nullable=False),
    sa.Column('SlugEn', sa.String(length=255), nullable=True),
    sa.Column('SlugAr', sa.String(length=255), nullable=True),
    sa.Column('Description', sa.Text(), nullable=True),
    sa.Column('IsActive', sa.Boolean(), nullable=False),
    sa.Column('IsDeleted', sa.Boolean(), nullable=False),
    sa.Column('CreatedAt', sa.DateTime(), nullable=False),
    sa.Column('CreatedBy', sa.String(length=36), nullable=True),
    sa.Column('UpdatedAt', sa.DateTime(), nullable=True),
    sa.Column('UpdatedBy', sa.String(length=36), nullable=True),
    sa.Column('DeletedAt', sa.DateTime(), nullable=True),
    sa.Column('DeletedBy', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('Categories',
    sa.Column('Id', sa.String(length=36), nullable=False),
    sa.Column('ParentId', sa.String(length=36), nullable=True),
    sa.Column('Title', sa.String(length=255), nullable=False),
    sa.Column('TitleEn', sa.String(length=255), nullable=True),
    sa.Column('TitleAr', sa.String(length=255), nullable=True),
    sa.Column('Slug', sa.String(length=255), nullable=False),
    sa.Column('SlugEn', sa.String(length=255), nullable=True),
    sa.Column('SlugAr', sa.String(length=255), nullable=True),
    sa.Column('Description', sa.Text(), nullable=True),
    sa.Column('DescriptionEn', sa.Text(), nullable=True),
    sa.Column('DescriptionAr', sa.Text(), nullable=True),
    sa.Column('SortOrder', sa.Integer(), nullable=False),
    sa.Column('IsActive', sa.Boolean(), nullable=False),
    sa.Column('IsDeleted', sa.Boolean(), nullable=False),
    sa.Column('CreatedAt', sa.DateTime(), nullable=False),
    sa.Column('CreatedBy', sa.String(length=36), nullable=True),
    sa.Column('UpdatedAt', sa.DateTime(), nullable=True),
    sa.Column('UpdatedBy', sa.String(length=36), nullable=True),
    sa.Column('DeletedAt', sa.DateTime(), nullable=True),
    sa.Column('DeletedBy', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['ParentId'], ['Categories.Id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('Likes',
    sa.Column('Id', sa.String(length=36), nullable=False),
    sa.Column('UserId', sa.String(length=36), nullable=False),
    sa.Column('TargetType', sa.String(length=20), nullable=False),
    sa.Column('TargetId', sa.String(length=36), nullable=False),
    sa.Column('CreatedAt', sa.DateTime(), nullable=False),
    sa.Column('IsDeleted', sa.Boolean(), nullable=False),
    sa.Column('DeletedAt', sa.DateTime(), nullable=True),
    sa.Column('DeletedBy', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('Id'),
    sa.UniqueConstraint('UserId', 'TargetType', 'TargetId', name='UQ_Likes_User_Target')
    )
    op.create_index('IX_Likes_Target', 'Likes', ['TargetType', 'TargetId'], unique=False)
    op.create_table('Blogs',
    sa.Column('Id', sa.String(length=36), nullable=False),
    sa.Column('BlogCategoryId', sa.String(length=36), nullable=True),
    sa.Column('AuthorId', sa.String(length=36), nullable=True),
    sa.Column('Title', sa.String(length=255), nullable=False),
    sa.Column('TitleEn', sa.String(length=255), nullable=True),
    sa.Column('TitleAr', sa.String(length=255), nullable=True),
    sa.Column('Slug', sa.String(length=255), nullable=False),
    sa.Column('SlugEn', sa.String(length=255), nullable=True),
    sa.Column('SlugAr', sa.String(length=255), nullable=True),
    sa.Column('Excerpt', sa.String(length=1000), nullable=True),
    sa.Column('ExcerptEn', sa.String(length=1000), nullable=True),
    sa.Column('ExcerptAr', sa.String(length=1000), nullable=True),
    sa.Column('Body', sa.Text(), nullable=True),
    sa.Column('BodyEn', sa.Text(), nullable=True),
    sa.Column('BodyAr', sa.Text(), nullable=True),
    sa.Column('FeaturedImageUrl', sa.String(length=500), nullable=True),
    sa.Column('IsPublished', sa.Boolean(), nullable=False),
    sa.Column('PublishedAt', sa.DateTime(), nullable=True),
    sa.Column('Views', sa.Integer(), nullable=False),
    sa.Column('IsDeleted', sa.Boolean(), nullable=False),
    sa.Column('CreatedAt', sa.DateTime(), nullable=False),
    sa.Column('CreatedBy', sa.String(length=36), nullable=True),
    sa.Column('UpdatedAt', sa.DateTime(), nullable=True),
    sa.Column('UpdatedBy', sa.String(length=36), nullable=True),
    sa.Column('DeletedAt', sa.DateTime(), nullable=True),
    sa.Column('DeletedBy', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['BlogCategoryId'], ['BlogCategories.Id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('Products',
    sa.Column('Id', sa.String(length=36), nullable=False),
    sa.Column('CategoryId', sa.String(length=36), nullable=True),
    sa.Column('SKU', sa.String(length=100), nullable=True),
    sa.Column('Title', sa.String(length=255), nullable=False),
    sa.Column('TitleEn', sa.String(length=255), nullable=True),
    sa.Column('TitleAr', sa.String(length=255), nullable=True),
    sa.Column('Slug', sa.String(length=255), nullable=False),
    sa.Column('SlugEn', sa.String(length=255), nullable=True),
    sa.Column('SlugAr', sa.String(length=255), nullable=True),
    sa.Column('ShortDescription', sa.String(length=1000), nullable=True),
    sa.Column('ShortDescriptionEn', sa.String(length=1000), nullable=True),
    sa.Column('ShortDescriptionAr', sa.String(length=1000), nullable=True),
    sa.Column('Description', sa.Text(), nullable=True),
    sa.Column('DescriptionEn', sa.Text(), nullable=True),
    sa.Column('DescriptionAr', sa.Text(), nullable=True),
    sa.Column('Price', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('Stock', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('IsActive', sa.Boolean(), nullable=False),
    sa.Column('IsFeatured', sa.Boolean(), nullable=False),
    sa.Column('MainImageUrl', sa.String(length=500), nullable=True),
    sa.Column('MetaTitle', sa.String(length=255), nullable=True),
    sa.Column('MetaDescription', sa.String(length=500), nullable=True),
    sa.Column('MetaKeywords', sa.String(length=500), nullable=True),
    sa.Column('IsDeleted', sa.Boolean(), nullable=False),
    sa.Column('CreatedAt', sa.DateTime(), nullable=False),
    sa.Column('CreatedBy', sa.String(length=36), nullable=True),
    sa.Column('UpdatedAt', sa.DateTime(), nullable=True),
    sa.Column('UpdatedBy', sa.String(length=36), nullable=True),
    sa.Column('DeletedAt', sa.DateTime(), nullable=True),
    sa.Column('DeletedBy', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['CategoryId'], ['Categories.Id'], ),
    sa.PrimaryKeyConstraint('Id'),
    sa.UniqueConstraint('SKU')
    )
    op.create_table('BlogComments',
    sa.Column('Id', sa.String(length=36), nullable=False),
    sa.Column('BlogId', sa.String(length=36), nullable=False),
    sa.Column('ParentId', sa.String(length=36), nullable=True),
    sa.Column('UserId', sa.String(length=36), nullable=True),
    sa.Column('Body', sa.Text(), nullable=False),
    sa.Column('BodyEn', sa.Text(), nullable=True),
    sa.Column('BodyAr', sa.Text(), nullable=True),
    sa.Column('IsApproved', sa.Boolean(), nullable=False),
    sa.Column('IsDeleted', sa.Boolean(), nullable=False),
    sa.Column('CreatedAt', sa.DateTime(), nullable=False),
    sa.Column('CreatedBy', sa.String(length=36), nullable=True),
    sa.Column('UpdatedAt', sa.DateTime(), nullable=True),
    sa.Column('UpdatedBy', sa.String(length=36), nullable=True),
    sa.Column('DeletedAt', sa.DateTime(), nullable=True),
    sa.Column('DeletedBy', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['BlogId'], ['Blogs.Id'], ),
    sa.ForeignKeyConstraint(['ParentId'], ['BlogComments.Id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('ProductComments',
    sa.Column('Id', sa.String(length=36), nullable=False),
    sa.Column('ProductId', sa.String(length=36), nullable=False),
    sa.Column('ParentId', sa.String(length=36), nullable=True),
    sa.Column('UserId', sa.String(length=36), nullable=True),
    sa.Column('Body', sa.Text(), nullable=False),
    sa.Column('BodyEn', sa.Text(), nullable=True),
    sa.Column('BodyAr', sa.Text(), nullable=True),
    sa.Column('Rating', sa.Integer(), nullable=True),
    sa.Column('IsApproved', sa.Boolean(), nullable=False),
    sa.Column('IsDeleted', sa.Boolean(), nullable=False),
    sa.Column('CreatedAt', sa.DateTime(), nullable=False),
    sa.Column('CreatedBy', sa.String(length=36), nullable=True),
    sa.Column('UpdatedAt', sa.DateTime(), nullable=True),
    sa.Column('UpdatedBy', sa.String(length=36), nullable=True),
    sa.Column('DeletedAt', sa.DateTime(), nullable=True),
    sa.Column('DeletedBy', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['ParentId'], ['ProductComments.Id'], ),
    sa.ForeignKeyConstraint(['ProductId'], ['Products.Id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('ProductImages',
    sa.Column('Id', sa.String(length=36), nullable=False),
    sa.Column('ProductId', sa.String(length=36), nullable=False),
    sa.Column('ImageUrl', sa.String(length=500), nullable=False),
    sa.Column('AltText', sa.String(length=255), nullable=True),
    sa.Column('AltTextEn', sa.String(length=255), nullable=True),
    sa.Column('AltTextAr', sa.String(length=255), nullable=True),
    sa.Column('IsPrimary', sa.Boolean(), nullable=False),
    sa.Column('SortOrder', sa.Integer(), nullable=False),
    sa.Column('IsDeleted', sa.Boolean(), nullable=False),
    sa.Column('CreatedAt', sa.DateTime(), nullable=False),
    sa.Column('CreatedBy', sa.String(length=36), nullable=True),
    sa.Column('UpdatedAt', sa.DateTime(), nullable=True),
    sa.Column('UpdatedBy', sa.String(length=36), nullable=True),
    sa.Column('DeletedAt', sa.DateTime(), nullable=True),
    sa.Column('DeletedBy', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['ProductId'], ['Products.Id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ProductImages')
    op.drop_table('ProductComments')
    op.drop_table('BlogComments')
    op.drop_table('Products')
    op.drop_table('Blogs')
    op.drop_index('IX_Likes_Target', table_name='Likes')
    op.drop_table('Likes')
    op.drop_table('Categories')
    op.drop_table('BlogCategories')
    # ### end Alembic commands ###

